description: "This research project develops training materials for researchers wanting to learn to build project
websites in GitHub with GitHub Pages."
email: "nvallej1@jhu.edu"
remote_theme: pages-themes/time-machine@v0.2.0
